# Generated by Django 5.0.7 on 2024-07-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('race', models.CharField(choices=[('gnome', 'Gnome'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('human', 'Human')], max_length=50)),
                ('char_class', models.CharField(choices=[('mage', 'Mage')], max_length=50)),
                ('strength_value', models.IntegerField()),
                ('agility_value', models.IntegerField()),
                ('constitution_value', models.IntegerField()),
                ('intelligence_value', models.IntegerField()),
                ('charisma_value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
