# Generated by Django 5.0.7 on 2024-07-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_classes', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='char_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_classes.charclass'),
        ),
    ]
